# Generated by Django 5.2.2 on 2025-06-09 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="airesumetailor",
            name="tailored_resume",
        ),
    ]
