# Generated by Django 5.2.2 on 2025-06-06 18:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
